shim-version: v0.2.15@sha256:5ca748b384b78b7e686b57ca66d9b3c552038ebab2ce60305004f76e573a8458
cvm-version: 0.5.8
cpus: 16
memory: 65536
gpus: full

models:
  - name: "whisper-large-v3-turbo"
    repo: "openai/whisper-large-v3-turbo@41f01f3fe87f28c78e2fbf8b568835947dd65ed9"
    mpk: "dd81839982fa01a289f7b60613055e4e1f789503c25a3535b75d53841f7f5b78_1622474752_55d2c545-4d89-5658-9ffd-ce0b4d07ac36"

containers:
  - name: "whisper-large-v3-turbo"
    image: ""
    args: [
      "--runtime", "nvidia",
      "--gpus", "all",
      "--ipc", "host",
      "ghcr.io/tinfoilsh/vllm-openai-audio:v0.0.2@sha256:118f9b8188666e221f785444560d72094a5298fe4bd373ec49c2b64a99611e9d",
      "--model", "/tinfoil/mpk/mpk-dd81839982fa01a289f7b60613055e4e1f789503c25a3535b75d53841f7f5b78",
      "--served-model-name", "whisper-large-v3-turbo",
      "--task", "transcription",
      "--port", "8001"
    ]

shim:
  listen-port: 443
  upstream-port: 8001
  publish-attestation: true
  tls-challenge: dns
  control-plane: https://api.tinfoil.sh
  paths:
    - /v1/audio/transcriptions
    - /metrics
    - /health
